//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoderTrack
{
    using System;
    using System.Collections.Generic;
    
    public partial class MRN
    {
        public System.DateTime Date { get; set; }
        public string ChartNo { get; set; }
        public string CompanyCode { get; set; }
        public string MRN1 { get; set; }
        public int AssessmentID { get; set; }
        public System.DateTime DateReceived { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
        public Nullable<decimal> TotalPay { get; set; }
        public int EmployeeId { get; set; }
    
        public virtual Assessment Assessment { get; set; }
        public virtual Company Company { get; set; }
    }
}
